spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sport_goods?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useSSL=false
      username: root
      password: 135223
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'   #验证连接
      enable: true
      # stat-view-servlet:
      #   enabled: true
      #   login-username: root
      #   login-password: 135223
      #   url-pattern: /druid/*

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:com/wlj/sportgoods/*/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
  - /index.html*
  - /sys/index
  - /file/**
  - /sys/toLogin*
  - /sys/toRegister*
  - /role/getAllRoles*
  - /user/register*
  - /login/login
  - /login/getCode
  - /sys/goodsShop*
  - /sys/goodDetail**
  - /goods/loadAllGoods*
  - /userGoods/getSales
  - /resources/**
  login-url: /sys/toLogin
  log-out-url: /login/logout*
  authc-urls:
  - /**
server:
  port: 8888